name: Playtomic Calendar Sync

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Virtual Environment
        run: |
          python3 -m venv venv
          ./venv/bin/pip install --upgrade pip
          if [ -f requirements.txt ]; then ./venv/bin/pip install -r requirements.txt; fi

      - name: Run Playtomic Sync Script
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
        run: ./venv/bin/python sync.py
